name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-for-production:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for lightsail
      run: docker build . --file Dockerfile --tag lineus-dot-dev-prod:$(date +%s)
  
  build-for-dev:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for dev
      run: docker build . --file Dockerfile --tag lineus-dot-dev:$(data +%s)